---
swagger: "2.0"
info:
  description: "A assistant for wanfang team"
  version: "1.0.0"
  title: "WFTeam"
  contact:
    email: "hueidou163@gmail.com"
  license:
    name: "MIT License"
    url: "https://github.com/hueidou/WFTeam/blob/master/LICENSE"
host: "localhost:8000"
basePath: "/api"
tags:
- name: "user"
  description: "用户"
  externalDocs:
    description: "Find out more about our store"
    url: "http://swagger.io"
schemes:
- "http"
paths:
  /user/login:
    post:
      tags:
      - "user"
      x-swagger-router-controller: "User"
      summary: "登录"
      description: ""
      operationId: "loginUser"
      produces:
      - "application/json"
      parameters:
      - name: "body"
        in: "body"
        description: "The user name for login"
        required: true
        schema:
          $ref: "#/definitions/LoginUser"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/LoginUser"
          headers:
            X-Rate-Limit:
              type: "integer"
              format: "int32"
              description: "calls per hour allowed by the user"
            X-Expires-After:
              type: "string"
              format: "date-time"
              description: "date in UTC when token expires"
        400:
          description: "Invalid username/password supplied"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  LoginUser:
    type: "object"
    properties:
      userName:
        type: "string"
externalDocs:
  description: "接口说明"
  url: "https://github.com/hueidou/WFTeam/blob/master/server/README.md"
